import type { Card } from "@/lib/types";

const clone = <T>(value: T): T => {
  if (typeof structuredClone === "function") {
    return structuredClone(value);
  }
  return JSON.parse(JSON.stringify(value));
};

export const CARD_LIBRARY: Card[] = [
  {
    id: "r1",
    name: "Bit Shift",
    color: "red",
    type: "primary",
    value: 5,
    description: "Standard compile strike. Solid baseline damage.",
    manaCost: 2,
    meta: { attack: { flavor: "normal" } },
  },
  {
    id: "r2",
    name: "Kernel Panic",
    color: "red",
    type: "primary",
    value: 6,
    description: "Critical compile that spikes damage output.",
    manaCost: 3,
    meta: { attack: { flavor: "critical", criticalMultiplier: 1.5 } },
  },
  {
    id: "r3",
    name: "True Ping",
    color: "red",
    type: "primary",
    value: 5,
    description: "Bypasses shields and lands true damage.",
    manaCost: 4,
    meta: { attack: { flavor: "true", bypassShield: true } },
  },
  {
    id: "r4",
    name: "Omni Loop",
    color: "red",
    type: "primary",
    value: 4,
    description: "Deals damage and siphons it back as omnivamp.",
    manaCost: 3,
    meta: { attack: { flavor: "omnivamp", lifestealPct: 0.5 } },
  },
  {
    id: "r5",
    name: "Thermal Leak",
    color: "red",
    type: "primary",
    value: 3,
    description: "Seeds lingering burn damage over time.",
    manaCost: 3,
    meta: { attack: { flavor: "dot", dot: { damage: 2, duration: 3 } } },
  },
  {
    id: "r6",
    name: "Overflow Crash",
    color: "red",
    type: "primary",
    value: 8,
    description: "Heavy burst that shrugs off mitigation.",
    manaCost: 4,
    meta: { attack: { flavor: "normal", bypassShield: true } },
  },
  {
    id: "r7",
    name: "Breakpoint Barrage",
    color: "red",
    type: "primary",
    value: 7,
    description: "Critical rain dealing serious bursts.",
    manaCost: 5,
    meta: { attack: { flavor: "critical", criticalMultiplier: 2 } },
  },
  {
    id: "r8",
    name: "Hex Burn",
    color: "red",
    type: "primary",
    value: 5,
    description: "Hybrid hit that also applies code decay.",
    manaCost: 3,
    meta: { attack: { flavor: "dot", dot: { damage: 3, duration: 2 } } },
  },
  {
    id: "r9",
    name: "Pulse Divide",
    color: "red",
    type: "primary",
    value: 6,
    description: "Omnivamp strike tuned for sustain.",
    manaCost: 4,
    meta: { attack: { flavor: "omnivamp", lifestealPct: 0.35 } },
  },
  {
    id: "r10",
    name: "Crash Override",
    color: "red",
    type: "primary",
    value: 9,
    description: "True damage burst that ignores shields.",
    manaCost: 5,
    meta: { attack: { flavor: "true", bypassShield: true } },
  },
  {
    id: "r11",
    name: "Packet Storm",
    color: "red",
    type: "primary",
    value: 4,
    description: "Multi-hit strike that weakens defenses.",
    manaCost: 3,
    meta: { attack: { flavor: "normal" }, utility: { enemyWeaken: 2 } },
  },
  {
    id: "r12",
    name: "Protocol Spear",
    color: "red",
    type: "primary",
    value: 7,
    description: "Critical jab that increases next attack.",
    manaCost: 4,
    meta: { attack: { flavor: "critical", criticalMultiplier: 1.8 }, utility: { attackBuff: 2 } },
  },
  {
    id: "r13",
    name: "Logic Bomb",
    color: "red",
    type: "primary",
    value: 5,
    description: "Delays detonation for bonus damage next turn.",
    manaCost: 3,
    meta: { attack: { flavor: "dot", dot: { damage: 4, duration: 1 } } },
  },
  {
    id: "r14",
    name: "Neon Lancer",
    color: "red",
    type: "primary",
    value: 6,
    description: "Pierces shields and refunds 1 mana if lethal.",
    manaCost: 4,
    meta: { attack: { flavor: "true", bypassShield: true } },
  },
  {
    id: "r15",
    name: "Binary Surge",
    color: "red",
    type: "primary",
    value: 4,
    description: "Rapid strike that draws a card if it crits.",
    manaCost: 2,
    meta: { attack: { flavor: "critical", criticalMultiplier: 1.4 }, utility: { draw: 1 } },
  },
  {
    id: "r16",
    name: "Kernel Lance",
    color: "red",
    type: "primary",
    value: 8,
    description: "Heavy thrust that damages attacker when blocked.",
    manaCost: 5,
    meta: { attack: { flavor: "normal" } },
  },
  {
    id: "r17",
    name: "Cobalt Cascade",
    color: "red",
    type: "primary",
    value: 3,
    description: "Low-cost strike that fuels Overload stacks.",
    manaCost: 1,
    meta: { attack: { flavor: "normal" } },
  },
  {
    id: "r18",
    name: "Volt Snapshot",
    color: "red",
    type: "primary",
    value: 6,
    description: "Applies minor burn and restores 1 mana.",
    manaCost: 3,
    meta: { attack: { flavor: "dot", dot: { damage: 2, duration: 2 } } },
  },
  {
    id: "r19",
    name: "Ghost Pulse",
    color: "red",
    type: "primary",
    value: 5,
    description: "Bypasses shields and heals for half damage dealt.",
    manaCost: 4,
    meta: { attack: { flavor: "true", bypassShield: true, lifestealPct: 0.5 } },
  },
  {
    id: "r20",
    name: "Cataclysm Loop",
    color: "red",
    type: "primary",
    value: 10,
    description: "Expensive finisher that doubles damage in sudden death.",
    manaCost: 6,
    meta: { attack: { flavor: "critical", criticalMultiplier: 2.2 } },
  },
  {
    id: "y1",
    name: "Stack Guard",
    color: "yellow",
    type: "primary",
    value: 6,
    description: "Blocks the next payload of damage.",
    manaCost: 2,
    meta: { defense: { block: 6 } },
  },
  {
    id: "y2",
    name: "Mirror Patch",
    color: "yellow",
    type: "primary",
    value: 5,
    description: "Reflects incoming packets back.",
    manaCost: 3,
    meta: { defense: { block: 3, deflect: 4 } },
  },
  {
    id: "y3",
    name: "Sandbox Kernel",
    color: "yellow",
    type: "primary",
    value: 4,
    description: "Ignores incoming debuffs for a cycle.",
    manaCost: 3,
    meta: { defense: { block: 4, debuffImmunity: true } },
  },
  {
    id: "y4",
    name: "Restore Point",
    color: "yellow",
    type: "primary",
    value: 0,
    description: "Heals core integrity.",
    manaCost: 3,
    meta: { defense: { heal: 6 } },
  },
  {
    id: "y5",
    name: "Null Shield",
    color: "yellow",
    type: "primary",
    value: 8,
    description: "Heavy block generation.",
    manaCost: 4,
    meta: { defense: { block: 8 } },
  },
  {
    id: "y6",
    name: "Absorb Loop",
    color: "yellow",
    type: "primary",
    value: 5,
    description: "Blocks and recovers a little.",
    manaCost: 3,
    meta: { defense: { block: 5, heal: 3 } },
  },
  {
    id: "y7",
    name: "Quantum Parry",
    color: "yellow",
    type: "primary",
    value: 4,
    description: "Deflects big swings back.",
    manaCost: 4,
    meta: { defense: { block: 4, deflect: 6 } },
  },
  {
    id: "y8",
    name: "Clean Room",
    color: "yellow",
    type: "primary",
    value: 3,
    description: "Cleanses ongoing damage effects.",
    manaCost: 2,
    meta: { defense: { block: 3, cleanse: true } },
  },
  {
    id: "y9",
    name: "System Reboot",
    color: "yellow",
    type: "primary",
    value: 0,
    description: "Massive heal and debuff purge.",
    manaCost: 5,
    meta: { defense: { heal: 10, cleanse: true } },
  },
  {
    id: "y10",
    name: "Fortify Mesh",
    color: "yellow",
    type: "primary",
    value: 7,
    description: "Stacks a sturdy barrier for two turns.",
    manaCost: 4,
    meta: { defense: { block: 7 } },
  },
  {
    id: "y11",
    name: "Parity Patch",
    color: "yellow",
    type: "primary",
    value: 4,
    description: "Reflects half the next damage instance.",
    manaCost: 3,
    meta: { defense: { block: 4, deflect: 4 } },
  },
  {
    id: "y12",
    name: "Safe Mode",
    color: "yellow",
    type: "primary",
    value: 2,
    description: "Small block that also boosts Override stacks.",
    manaCost: 1,
    meta: { defense: { block: 2 } },
  },
  {
    id: "y13",
    name: "Checksum Seal",
    color: "yellow",
    type: "primary",
    value: 6,
    description: "Blocks and prevents crit damage next turn.",
    manaCost: 4,
    meta: { defense: { block: 6, debuffImmunity: true } },
  },
  {
    id: "y14",
    name: "Recursive Shield",
    color: "yellow",
    type: "primary",
    value: 5,
    description: "If broken, instantly draw a defense card.",
    manaCost: 3,
    meta: { defense: { block: 5 }, utility: { draw: 1 } },
  },
  {
    id: "y15",
    name: "Polarize Field",
    color: "yellow",
    type: "primary",
    value: 4,
    description: "Reduces next attack's damage by half.",
    manaCost: 2,
    meta: { defense: { block: 4 }, utility: { enemyWeaken: 4 } },
  },
  {
    id: "y16",
    name: "Crash Recover",
    color: "yellow",
    type: "primary",
    value: 0,
    description: "Restore HP equal to cards in discard pile (max 8).",
    manaCost: 4,
    meta: { defense: { heal: 8 } },
  },
  {
    id: "y17",
    name: "Firewall Bloom",
    color: "yellow",
    type: "primary",
    value: 7,
    description: "Blocks and cleanses burn/dot effects.",
    manaCost: 4,
    meta: { defense: { block: 7, cleanse: true } },
  },
  {
    id: "y18",
    name: "Quantum Sheath",
    color: "yellow",
    type: "primary",
    value: 5,
    description: "Converts block into healing if no damage arrives.",
    manaCost: 3,
    meta: { defense: { block: 5, heal: 3 } },
  },
  {
    id: "y19",
    name: "Failover Node",
    color: "yellow",
    type: "primary",
    value: 3,
    description: "Small block that recharges 1 mana next turn.",
    manaCost: 2,
    meta: { defense: { block: 3 }, utility: { attackBuff: 1 } },
  },
  {
    id: "y20",
    name: "Guardian Matrix",
    color: "yellow",
    type: "primary",
    value: 9,
    description: "Gigantic shield that also deflects.",
    manaCost: 5,
    meta: { defense: { block: 9, deflect: 5 } },
  },
  {
    id: "g1",
    name: "Overclock",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Boosts the next attack routine.",
    manaCost: 2,
    meta: { utility: { attackBuff: 3 } },
  },
  {
    id: "g2",
    name: "Compiler Macro",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Improves offense and stabilizes defense.",
    manaCost: 3,
    meta: { utility: { attackBuff: 3, defenseBuff: 2 } },
  },
  {
    id: "g3",
    name: "Entropy Jam",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Weakens the next hostile strike.",
    manaCost: 2,
    meta: { utility: { enemyWeaken: 3 } },
  },
  {
    id: "g4",
    name: "Payload Spike",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Adds throughput and extra draw.",
    manaCost: 3,
    meta: { utility: { attackBuff: 2, draw: 1 } },
  },
  {
    id: "g5",
    name: "Shield Script",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Layered defense logic.",
    manaCost: 3,
    meta: { utility: { defenseBuff: 4 } },
  },
  {
    id: "g6",
    name: "Adaptive Loop",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Balanced boost with small heal.",
    manaCost: 4,
    meta: { utility: { attackBuff: 2, defenseBuff: 2, heal: 2 } },
  },
  {
    id: "g7",
    name: "Flux Anchor",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Steadies systems and weakens foes.",
    manaCost: 3,
    meta: { utility: { defenseBuff: 2, enemyWeaken: 2 } },
  },
  {
    id: "g8",
    name: "Directive Bloom",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Quietly grows the next strike potential.",
    manaCost: 2,
    meta: { utility: { attackBuff: 2 } },
  },
  {
    id: "g9",
    name: "Signal Cache",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Refills hand and primes output.",
    manaCost: 3,
    meta: { utility: { draw: 1, attackBuff: 1 } },
  },
  {
    id: "g10",
    name: "Manifold Bloom",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Grant +1 mana next two turns.",
    manaCost: 2,
    meta: { utility: { attackBuff: 1, defenseBuff: 1 } },
  },
  {
    id: "g11",
    name: "Cache Rewrite",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Discard your hand and draw three new cards.",
    manaCost: 3,
    meta: { utility: { draw: 3 } },
  },
  {
    id: "g12",
    name: "Trace Dampener",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Reduce damage over time by 2 for both players.",
    manaCost: 2,
    meta: { utility: { defenseBuff: 2 } },
  },
  {
    id: "g13",
    name: "Sandbox Clone",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Duplicate the last card you played.",
    manaCost: 4,
    meta: { utility: { draw: 1 } },
  },
  {
    id: "g14",
    name: "Keypair Surge",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Give next attack +3 value and lifesteal.",
    manaCost: 3,
    meta: { utility: { attackBuff: 3 } },
  },
  {
    id: "g15",
    name: "Entropy Buffer",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Next defense card gains +4 block.",
    manaCost: 2,
    meta: { utility: { defenseBuff: 4 } },
  },
  {
    id: "g16",
    name: "Quantum Reroute",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Swap mana pools with opponent for one turn.",
    manaCost: 4,
    meta: { utility: { enemyWeaken: 2 } },
  },
  {
    id: "g17",
    name: "Macro Loop",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Draw one attack and one defense card.",
    manaCost: 3,
    meta: { utility: { draw: 2 } },
  },
  {
    id: "g18",
    name: "Pulse Amplifier",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Next three attack cards gain +1 value.",
    manaCost: 3,
    meta: { utility: { attackBuff: 3 } },
  },
  {
    id: "g19",
    name: "Mirror Routine",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Copy enemy's last played card into your hand.",
    manaCost: 4,
    meta: { utility: { draw: 1 } },
  },
  {
    id: "g20",
    name: "Failsafe Bloom",
    color: "green",
    type: "supplementary",
    value: 0,
    description: "Heal 4 and cleanse if HP below 20.",
    manaCost: 3,
    meta: { utility: { heal: 4 } },
  },
];

export const CARD_LIBRARY_MAP: Record<string, Card> = CARD_LIBRARY.reduce(
  (acc, card) => {
    acc[card.id] = card;
    return acc;
  },
  {} as Record<string, Card>
);

export const DEFAULT_DECK_IDS = CARD_LIBRARY.map((card) => card.id);

export const cloneCard = (card: Card): Card => clone(card);

export const cardsFromIds = (ids: string[]): Card[] =>
  ids
    .map((id) => CARD_LIBRARY_MAP[id])
    .filter(Boolean)
    .map((card) => cloneCard(card!));

